blank_per_minute = {
    'kills/min' : 0,
    'deaths/min' : 0,
    'suicides/min' : 0,
    'avg_game_length' : 0,
    'caps/min' : 0,
    'saves/min' : 0,
    'flux_kills/min' : 0,
    'blitz_kills/min' : 0,
    'gravity_bomb_kills/min' : 0,
    'flux_deaths/min' : 0,
    'blitz_deaths/min' : 0,
    'gravity_bomb_deaths/min' : 0,
    'total_mins':0,
    'flux_mins':0,
    'blitz_mins':0,
    'grav_mins':0,
    'ctf_mins': 0,
    'siege_mins': 0,
    'deathmatch_mins': 0,
    'maps':{
        "Bakisi_Isle":0,
        "Hoven_Gorge":0,
        "Outpost_x12":0,
        "Korgon_Outpost":0,
        "Metropolis":0,
        "Blackwater_City":0,
        "Command_Center":0,
        'Aquatos_Sewers':0,
        "Blackwater_Dox":0,
        "Marcadia_Palace":0
    }
}

blank_per_game = {
    'kills/gm' : 0,
    'deaths/gm' : 0,
    'suicides/gm' : 0,
    'caps/gm' : 0,
    'saves/gm' : 0,
    'flux_kills/gm' :0,
    'blitz_kills/gm' : 0,
    'gravity_bomb_kills/gm' : 0,
    'flux_deaths/gm' : 0,
    'blitz_deaths/gm' : 0,
    'gravity_bomb_deaths/gm' :0,
    'flux_gms':0,
    'grav_gms': 0,
    'blitz_gms' :0,
    'maps':{
        "Bakisi_Isle":0,
        "Hoven_Gorge":0,
        "Outpost_x12":0,
        "Korgon_Outpost":0,
        "Metropolis":0,
        "Blackwater_City":0,
        "Command_Center":0,
        'Aquatos_Sewers':0,
        "Blackwater_Dox":0,
        "Marcadia_Palace":0
    }
}